# -*- coding: utf-8 -*-
"""pandaproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zKBG66OEIIpFsMW4XPQ2pRJlem81sKs
"""

import pandas as pd
import numpy as np

import plotly.express as px

import plotly.graph_objects as go

df = pd.read_csv('/content/apple_products.csv')
df

#df.head()

#print(df.isnull().sum())

#df.describe()

highest_rated = df.sort_values(by=['Star Rating'],ascending=False)
highest_rated = highest_rated.head(10)
#print(highest_rated['Product Name'])
iphone = highest_rated['Product Name'].value_counts()
label = iphone.index
value_counts = highest_rated['Number Of Ratings'] # This variable holds the counts
figure = px.bar(highest_rated, x = label , y = value_counts , title= "Number of ratings of highesr rated iphone") # Use value_counts here
figure.show()

